#ifndef MILODY_GAME_RETCODE_H
#define MILODY_GAME_RETCODE_H

#include <cstdint>

enum MILODY_API_RET_CODE: int64_t {
    MILODY_API_RET_OK = 0,
    MILODY_API_RET_UNEXPECTED_EXCEPTION = -11709394,
    MILODY_API_RET_FAILED = -1,

    MILODY_API_RET_AUDIO_FAILED = -1,

    MILODY_API_RET_CANCELED = -100,

    MILODY_API_RET_INITIALIZED = 1,
};

#endif //MILODY_MILODY_GAME_RETCODE_H
